"use client"
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Footers from "@/components/Footers";
import { useState } from "react";

const inter = Roboto({
  subsets: ["latin"],
  weight: ["300", "100", "900", "400", "500", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  
  return (
    <html lang="en">
      <body
        className={`${inter.className} relative  min-h-screen  w-screen flex flex-col   `}
      >
        <div>
          <Header  />
        </div>

        <main className="w-screen flex  items-center justify-center mb-40">
          {children}
        </main>
        <div className="absolute bottom-0 w-full h-24 flex items-center">
          <Footers />
        </div>
      </body>
    </html>
  );
}
